// 作成日: 2026-07-21 / 作成担当: Codex
// 最終更新日: 2026-07-21 (Codex) — 他の人へ渡せる、端末内だけのくらしと通院メモ。
import { useEffect, useMemo, useRef, useState } from "react";
import { db, blankEntry, extras, type AkariSettings, type LifeEntry } from "./db";

type Page = "home" | "record" | "history" | "clinic" | "settings";
type ClinicField = "meals" | "medicine" | "bath" | "work" | "condition" | "recorded" | "trouble";
const coreSections = [["sleep", "寝た・起きた時刻"], ["meals", "食事"], ["medicine", "薬"], ["note", "今日のメモ"], ["trouble", "困りごとのメモ"]] as const;
const clinicFields: readonly [ClinicField, string][] = [["meals", "食事"], ["medicine", "薬"], ["bath", "入浴"], ["work", "仕事・通所"], ["condition", "体調不良"], ["recorded", "記録した日"], ["trouble", "困りごとのメモ"]];
const prompts = ["今日あったこと、体調、明日のこと……", "通院で伝えたいこと、気になったこと……", "できたことも、できなかったことも、そのまま……"];
const today = () => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); };
const displayDate = (date: string) => new Intl.DateTimeFormat("ja-JP", { month: "long", day: "numeric", weekday: "short" }).format(new Date(`${date}T12:00:00`));
const timeChoices = Array.from({ length: 48 }, (_, i) => `${String(Math.floor(i / 2)).padStart(2, "0")}:${i % 2 ? "30" : "00"}`);
const defaultVisible = () => Object.fromEntries(coreSections.map(([key]) => [key, true]));
const defaultClinicFields = () => Object.fromEntries(clinicFields.map(([key]) => [key, true])) as Record<ClinicField, boolean>;
const meaningful = (entry: LifeEntry) => Boolean(entry.bedtimePrev || entry.wakeTime || entry.medicine || Object.values(entry.meals).some(Boolean) || Object.values(entry.activities).some(Boolean) || entry.note || entry.troubleNote);
const localDate = (daysAgo: number) => { const value = new Date(); value.setHours(12, 0, 0, 0); value.setDate(value.getDate() - daysAgo); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };

export default function GenericApp() {
  const [page, setPage] = useState<Page>("home");
  const [entries, setEntries] = useState<LifeEntry[]>([]);
  const [settings, setSettings] = useState<AkariSettings>({ id: "main", enabledExtras: {}, partnerName: false, visibleSections: defaultVisible(), clinicDays: 30, clinicFields: defaultClinicFields() });
  const [activeDate, setActiveDate] = useState(today());
  const [draft, setDraft] = useState<LifeEntry>(blankEntry(today()));
  const [notice, setNotice] = useState("");
  const importRef = useRef<HTMLInputElement>(null);
  const visible = { ...defaultVisible(), ...(settings.visibleSections ?? {}) };

  async function load() {
    const [savedEntries, saved] = await Promise.all([db.entries.orderBy("date").reverse().toArray(), db.settings.get("main")]);
    setEntries(savedEntries);
    setSettings(saved ? { ...saved, visibleSections: { ...defaultVisible(), ...(saved.visibleSections ?? {}) }, clinicDays: saved.clinicDays ?? 30, clinicFields: { ...defaultClinicFields(), ...(saved.clinicFields ?? {}) } } : { id: "main", enabledExtras: {}, partnerName: false, visibleSections: defaultVisible(), clinicDays: 30, clinicFields: defaultClinicFields() });
  }
  useEffect(() => { void load(); }, []);
  useEffect(() => { const found = entries.find((entry) => entry.date === activeDate); setDraft(found ? structuredClone(found) : blankEntry(activeDate)); }, [activeDate, entries]);
  useEffect(() => {
    const timer = window.setInterval(() => {
      const now = new Date(), yesterday = new Date(now); yesterday.setDate(now.getDate() - 1);
      const yesterdayDate = new Date(yesterday.getTime() - yesterday.getTimezoneOffset() * 60_000).toISOString().slice(0, 10);
      if (page !== "record" || activeDate !== yesterdayDate) return;
      const existing = entries.find((entry) => entry.date === activeDate);
      if (meaningful(draft) || existing) void db.entries.put({ ...draft, createdAt: existing?.createdAt ?? new Date().toISOString(), updatedAt: new Date().toISOString() }).then(load);
      setActiveDate(today()); setNotice("日付が変わったから、前の書きかけを残して今日の頁をひらいたよ。");
    }, 30_000);
    return () => window.clearInterval(timer);
  }, [activeDate, draft, entries, page]);

  async function save(close = false) {
    const before = entries.find((entry) => entry.date === activeDate);
    await db.entries.put({ ...draft, createdAt: before?.createdAt ?? new Date().toISOString(), updatedAt: new Date().toISOString() });
    await load(); setNotice(close ? "ここまでの記録を残したよ。" : "今日の記録を残したよ。"); if (close) setPage("home");
  }
  async function saveSettings(next: AkariSettings) { await db.settings.put(next); setSettings(next); setNotice("表示する項目を整えたよ。"); }
  function download(data: unknown, filename: string) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
  function exportAll() { download({ app: "kurashi-tsuin-memo", version: 1, exportedAt: new Date().toISOString(), entries, settings }, `kurashi-tsuin-memo-${today()}.json`); void saveSettings({ ...settings, backupAt: new Date().toISOString() }); setNotice("すべての記録をJSONファイルとして端末のダウンロードに保存したよ。"); }
  async function importJson(file: File) { try { const parsed = JSON.parse(await file.text()) as { app?: string; entries?: LifeEntry[]; settings?: AkariSettings }; if (!Array.isArray(parsed.entries)) throw new Error("記録データが見つからない"); await db.transaction("rw", db.entries, db.settings, async () => { await db.entries.bulkPut(parsed.entries!); if (parsed.settings) await db.settings.put(parsed.settings); }); await load(); setNotice("JSONから記録を読み込んだよ。同じ日付は読み込んだ内容に置き換えたよ。"); } catch { setNotice("読み込めなかったよ。くらしと通院メモのJSONファイルか確認してね。"); } }

  return <main className="appShell generic"><header><button className="brand" onClick={() => setPage("home")} aria-label="くらしと通院メモのトップへ"><img src="./icon.svg" /><span>くらしと通院メモ<small>くらしのことと、通院で伝えたいことを残す</small></span></button><button className="quietButton" onClick={() => setPage("settings")}>設定</button></header>{notice && <p className="notice" role="status">{notice}</p>}
    {page === "home" && <Home entries={entries} onGo={setPage} />}
    {page === "record" && <Record date={activeDate} draft={draft} visible={visible} extrasEnabled={extras.filter(([key]) => settings.enabledExtras[key])} setDate={setActiveDate} setDraft={setDraft} onSave={() => void save()} onClose={() => void save(true)} />}
    {page === "history" && <History entries={entries} onOpen={(date) => { setActiveDate(date); setPage("record"); }} />}
    {page === "clinic" && <Clinic entries={entries} settings={settings} onSettings={() => setPage("settings")} onCopy={(text) => navigator.clipboard.writeText(text).then(() => setNotice("通院メモをコピーしたよ。診察で見せたり、貼り付けたりできるよ。"))} onDownload={download} />}
    {page === "settings" && <Settings settings={settings} onChange={(next) => void saveSettings(next)} onExport={exportAll} onImport={() => importRef.current?.click()} />}
    <input ref={importRef} className="hidden" type="file" accept="application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importJson(file); event.currentTarget.value = ""; }} />
  </main>;
}

function Home({ entries, onGo }: { entries: LifeEntry[]; onGo: (page: Page) => void }) { const current = entries.find((entry) => entry.date === today()); return <section className="home"><p className="eyebrow">{displayDate(today())}</p><h1>{current && meaningful(current) ? "今日のことは、もう残っている。" : "今日のことを、ひとつだけ残す。"}</h1><p className="intro">記録は採点ではない。書けたぶんだけ、あとで自分を助けるメモになる。</p><button className="primaryAction" onClick={() => onGo("record")}>今日を記録する <span>→</span></button><div className="homeLinks"><button onClick={() => onGo("clinic")}>通院メモをつくる <span>期間と項目を選んでコピー・保存</span></button><button onClick={() => onGo("history")}>過去の記録を見る <span>前の日にも書き足せる</span></button><button onClick={() => onGo("settings")}>項目と保存を整える <span>表示するものを選ぶ</span></button></div></section>; }

function Record({ date, draft, visible, extrasEnabled, setDate, setDraft, onSave, onClose }: { date: string; draft: LifeEntry; visible: Record<string, boolean>; extrasEnabled: readonly (readonly [string, string])[]; setDate: (value: string) => void; setDraft: (value: LifeEntry) => void; onSave: () => void; onClose: () => void }) { const time = (label: string, key: "bedtimePrev" | "wakeTime") => <label className="timeField"><span>{label}</span><select value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })}><option value="">まだ書いていない</option>{timeChoices.map((value) => <option key={value}>{value}</option>)}</select></label>; return <section className="paper"><div className="pageTitle"><div><p className="eyebrow">一日の記録</p><h1>{displayDate(date)}</h1></div><input type="date" value={date} onChange={(event) => setDate(event.target.value)} aria-label="記録する日" /></div>{visible.sleep && <div className="formBlock">{time("前夜に寝た時刻", "bedtimePrev")}{time("今朝起きた時刻", "wakeTime")}</div>}{visible.meals && <Checks title="食事" choices={[["breakfast", "朝食"], ["lunch", "昼食"], ["dinner", "夕食"], ...(extrasEnabled.some(([key]) => key === "lateSnack") ? [["lateSnack", "夜食"]] : [])] as unknown as readonly (readonly [string, string])[]} values={draft.meals} onChange={(key) => setDraft({ ...draft, meals: { ...draft.meals, [key]: !draft.meals[key as keyof LifeEntry["meals"]] } })} />}{visible.medicine && <Checks title="薬" choices={[["medicine", "飲んだ"]]} values={{ medicine: draft.medicine }} onChange={() => setDraft({ ...draft, medicine: !draft.medicine })} />}{extrasEnabled.filter(([key]) => key !== "lateSnack").length > 0 && <Checks title="今日したこと" choices={extrasEnabled.filter(([key]) => key !== "lateSnack")} values={draft.activities} onChange={(key) => setDraft({ ...draft, activities: { ...draft.activities, [key]: !draft.activities[key] } })} />}{visible.note && <label className="noteField"><span>今日のメモ</span><textarea value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })} placeholder={prompts[new Date(date).getDate() % prompts.length]} rows={5} /></label>}{visible.trouble && <label className="noteField"><span>困りごとのメモ</span><small>通院などで伝えたい事実を残す欄。コピー・JSON書き出しに含めるかは、その都度選べる。</small><textarea value={draft.troubleNote ?? ""} onChange={(event) => setDraft({ ...draft, troubleNote: event.target.value })} placeholder="例: 外出先で疲れて予定を切り上げた。家事の段取りが組めなかった……" rows={3} /></label>}<div className="recordActions"><button className="softButton" onClick={onClose}>今日はここまで</button><button className="primaryAction small" onClick={onSave}>記録を残す <span>✦</span></button></div></section>; }

function Checks({ title, choices, values, onChange }: { title: string; choices: readonly (readonly [string, string])[]; values: Record<string, boolean>; onChange: (key: string) => void }) { return <fieldset className="checkGroup"><legend>{title}</legend><div>{choices.map(([key, label]) => <label key={key} className={values[key] ? "checked" : ""}><input type="checkbox" checked={Boolean(values[key])} onChange={() => onChange(key)} /><i>✦</i>{label}</label>)}</div></fieldset>; }
function History({ entries, onOpen }: { entries: LifeEntry[]; onOpen: (date: string) => void }) { return <section className="paper"><p className="eyebrow">過去の記録</p><h1>記録をひらく</h1>{entries.length === 0 ? <p className="empty">まだ記録はないよ。最初の一頁は、今日からで大丈夫。</p> : <div className="pastList">{entries.map((entry) => <button key={entry.date} onClick={() => onOpen(entry.date)}><span>{displayDate(entry.date)}</span><small>{meaningful(entry) ? "記録あり" : "日付だけ"}</small><b>›</b></button>)}</div>}</section>; }

function Clinic({ entries, settings, onSettings, onCopy, onDownload }: { entries: LifeEntry[]; settings: AkariSettings; onSettings: () => void; onCopy: (text: string) => void; onDownload: (data: unknown, filename: string) => void }) { const [days, setDays] = useState(settings.clinicDays ?? 30); const [includeTroubles, setIncludeTroubles] = useState(Boolean(settings.clinicFields?.trouble)); const fields = { ...defaultClinicFields(), ...(settings.clinicFields ?? {}), trouble: includeTroubles }; const period = useMemo(() => entries.filter((entry) => days === "all" || entry.date >= localDate(Number(days) - 1)), [entries, days]); const report = makeReport(period, days, fields); return <section className="paper clinic"><p className="eyebrow">通院メモ</p><h1>伝えたいことを整える</h1><p className="clinicNote">記録がない日は、「していない」とは決めつけない。書いたぶんだけを、そのまま見せる。</p><fieldset className="settingsGroup"><legend>見る期間</legend><div className="periodButtons">{([7, 14, 30, 60, 90, "all"] as const).map((value) => <button key={value} className={days === value ? "selected" : ""} onClick={() => setDays(value)}>{value === "all" ? "すべて" : `過去${value}日`}</button>)}</div></fieldset><section className="clinicReport"><h2>通院に渡すメモ</h2><p>設定で選んだ項目だけが表示される。コピーは診察で貼り付けたり、画面を見せたりするためのもの。</p><label><input type="checkbox" checked={includeTroubles} onChange={(event) => setIncludeTroubles(event.target.checked)} />困りごとのメモも、今回だけ含める</label><pre>{report}</pre><div className="reportActions"><button className="softButton" onClick={() => onCopy(report)}>メモをコピー</button><button className="softButton" onClick={() => onDownload({ app: "kurashi-tsuin-memo", exportedAt: new Date().toISOString(), period: days, fields, entries: period }, `tsuin-memo-${today()}.json`)}>この期間をJSONにする</button></div><small>JSONは端末の「ダウンロード」へファイルとして保存される。メール添付や保管に使えるけれど、個人情報を含むことがあるから渡す相手は自分で選んでね。</small></section><button className="quietButton dark" onClick={onSettings}>通院メモに表示する項目を設定する</button></section>; }
function makeReport(entries: LifeEntry[], days: number | "all", fields: Record<ClinicField, boolean>) { const periodText = days === "all" ? "記録したすべての期間" : `過去${days}日`; const meals = entries.reduce((sum, entry) => sum + Number(entry.meals.breakfast) + Number(entry.meals.lunch) + Number(entry.meals.dinner), 0); const count = (key: string) => entries.filter((entry) => entry.activities[key]).length; const lines = [`通院メモ（${periodText}）`, `記録のある日: ${entries.length}日`]; if (fields.meals) lines.push(`食事: ${meals}回（朝・昼・夕として記録した分）`); if (fields.medicine) lines.push(`薬: ${entries.filter((entry) => entry.medicine).length}日（飲んだと記録した日）`); if (fields.bath) lines.push(`入浴: ${count("bath")}日（記録した日）`); if (fields.work) lines.push(`仕事・通所: ${count("work") + count("commute") + count("daycare")}日（記録した日）`); if (fields.condition) lines.push(`体調不良: ${count("condition")}日（記録した日）`); if (fields.recorded) lines.push(`メモを書いた日: ${entries.filter((entry) => entry.note.trim()).length}日`); if (fields.trouble) { const notes = entries.filter((entry) => entry.troubleNote?.trim()); lines.push("", "困りごとのメモ"); lines.push(...(notes.length ? notes.map((entry) => `・${entry.date.replace(/-/g, "/")}: ${entry.troubleNote!.trim()}`) : ["・この期間に記録はありません"])); } return lines.join("\n"); }

function Settings({ settings, onChange, onExport, onImport }: { settings: AkariSettings; onChange: (next: AkariSettings) => void; onExport: () => void; onImport: () => void }) { const visible = { ...defaultVisible(), ...(settings.visibleSections ?? {}) }; const fields = { ...defaultClinicFields(), ...(settings.clinicFields ?? {}) }; return <section className="paper"><p className="eyebrow">設定</p><h1>表示と保存を整える</h1><fieldset className="settingsGroup"><legend>記録する項目</legend><p>いらない項目は隠せる。必要になったら、いつでも戻せる。</p>{coreSections.map(([key, label]) => <label key={key}><input type="checkbox" checked={visible[key]} onChange={() => onChange({ ...settings, visibleSections: { ...visible, [key]: !visible[key] } })} />{label}</label>)}{extras.map(([key, label]) => <label key={key}><input type="checkbox" checked={Boolean(settings.enabledExtras[key])} onChange={() => onChange({ ...settings, enabledExtras: { ...settings.enabledExtras, [key]: !settings.enabledExtras[key] } })} />{label}</label>)}</fieldset><fieldset className="settingsGroup"><legend>通院メモに表示する項目</legend><p>コピーとJSONに入れる項目を選ぶ。困りごとのメモは毎回、通院画面でも確認できる。</p>{clinicFields.map(([key, label]) => <label key={key}><input type="checkbox" checked={fields[key]} onChange={() => onChange({ ...settings, clinicFields: { ...fields, [key]: !fields[key] } })} />{label}</label>)}</fieldset><section className="backup"><h2>記録をJSONに保存する</h2><p>押すと、すべての記録をJSONファイルにして端末の「ダウンロード」へ保存する。機種変更や、念のための避難に使える。</p>{settings.backupAt && <small>最後に保存した日: {new Date(settings.backupAt).toLocaleString("ja-JP")}</small>}<div><button className="softButton" onClick={onExport}>すべてをJSONにする</button><button className="softButton" onClick={onImport}>JSONを読み込む</button></div></section></section>; }
