// 作成日: 2026-07-21 / 作成担当: Codex
// 最終更新日: 2026-07-21 (Codex) — 通院時の記録を、各自で静かに整えられる形へ。
import { useEffect, useMemo, useRef, useState } from "react";
import { db, blankEntry, extras, type AppSettings, type LifeEntry } from "./db";

type Page = "home" | "record" | "history" | "clinic" | "settings" | "help";
type ClinicField = "meals" | "medicine" | "bath" | "work" | "condition" | "recorded" | "trouble";
type Theme = "night" | "paper" | "forest" | "rose";
const coreItems = [["sleep", "寝た・起きた時刻"], ["meals", "食事"], ["medicine", "薬"], ["note", "今日の日記"], ["trouble", "困りごとのメモ（通院時用）"]] as const;
const clinicItems: readonly [ClinicField, string][] = [["meals", "食事"], ["medicine", "薬の記録"], ["bath", "入浴"], ["work", "仕事"], ["condition", "体調不良"], ["recorded", "日記を書いた日"], ["trouble", "困りごとのメモ"]];
const prompts = ["今日あったこと、体調、明日のこと……", "外出したこと、楽しかったこと、困ったこと……", "できたことも、できなかったことも、そのまま……"];
const today = () => { const n = new Date(); return new Date(n.getTime() - n.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); };
const dateText = (date: string) => new Intl.DateTimeFormat("ja-JP", { month: "long", day: "numeric", weekday: "short" }).format(new Date(`${date}T12:00:00`));
const times = Array.from({ length: 48 }, (_, i) => `${String(Math.floor(i / 2)).padStart(2, "0")}:${i % 2 ? "30" : "00"}`);
const defaults = () => ({ visible: Object.fromEntries(coreItems.map(([k]) => [k, true])) as Record<string, boolean>, clinic: Object.fromEntries(clinicItems.map(([k]) => [k, true])) as Record<ClinicField, boolean> });
const localDate = (daysAgo: number) => { const d = new Date(); d.setHours(12, 0, 0, 0); d.setDate(d.getDate() - daysAgo); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };
const meaningful = (e: LifeEntry) => Boolean(e.bedtimePrev || e.wakeTime || e.medicine || Object.values(e.meals).some(Boolean) || Object.values(e.activities).some(Boolean) || e.note || e.troubleNote);

export default function GenericAppV3() {
  const base = defaults();
  const [page, setPage] = useState<Page>("home"), [entries, setEntries] = useState<LifeEntry[]>([]), [activeDate, setActiveDate] = useState(today()), [draft, setDraft] = useState<LifeEntry>(blankEntry(today())), [notice, setNotice] = useState("");
  const [settings, setSettings] = useState<AppSettings>({ id: "main", enabledExtras: {}, visibleSections: base.visible, clinicDays: 30, clinicFields: base.clinic, customItems: [], theme: "night" });
  const importRef = useRef<HTMLInputElement>(null);
  const visible = { ...base.visible, ...(settings.visibleSections ?? {}) };
  async function load() { const [saved, savedSettings] = await Promise.all([db.entries.orderBy("date").reverse().toArray(), db.settings.get("main")]); setEntries(saved); setSettings(savedSettings ? { ...savedSettings, visibleSections: { ...base.visible, ...(savedSettings.visibleSections ?? {}) }, clinicFields: { ...base.clinic, ...(savedSettings.clinicFields ?? {}) }, customItems: savedSettings.customItems ?? [], theme: savedSettings.theme ?? "night" } : { id: "main", enabledExtras: {}, visibleSections: base.visible, clinicDays: 30, clinicFields: base.clinic, customItems: [], theme: "night" }); }
  useEffect(() => { void load(); }, []);
  useEffect(() => { const found = entries.find((e) => e.date === activeDate); setDraft(found ? structuredClone(found) : blankEntry(activeDate)); }, [activeDate, entries]);
  async function save(close = false) { const old = entries.find((e) => e.date === activeDate); await db.entries.put({ ...draft, createdAt: old?.createdAt ?? new Date().toISOString(), updatedAt: new Date().toISOString() }); await load(); setNotice(close ? "ここまでの記録を残したよ。" : "今日の記録を残したよ。"); if (close) setPage("home"); }
  async function saveSettings(next: AppSettings) { await db.settings.put(next); setSettings(next); setNotice("設定を整えたよ。項目を外しても、過去の記録は消えないよ。"); }
  function download(data: unknown, filename: string) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); }
  function exportAll() { download({ app: "kurashi-tsuin-memo", version: 3, exportedAt: new Date().toISOString(), entries, settings }, `kurashi-tsuin-memo-${today()}.json`); void saveSettings({ ...settings, backupAt: new Date().toISOString() }); setNotice("すべての記録をJSONファイルとして端末のダウンロードに保存したよ。"); }
  async function importJson(file: File) { try { const data = JSON.parse(await file.text()) as { entries?: LifeEntry[]; settings?: AppSettings }; if (!Array.isArray(data.entries)) throw new Error(); await db.transaction("rw", db.entries, db.settings, async () => { await db.entries.bulkPut(data.entries!); if (data.settings) await db.settings.put(data.settings); }); await load(); setNotice("JSONを読み込んだよ。同じ日付は読み込んだ内容に置き換えたよ。"); } catch { setNotice("読み込めなかったよ。くらしと通院メモのJSONファイルか確認してね。"); } }
  return <main className={`appShell generic theme-${settings.theme ?? "night"}`}><header><button className="brand" onClick={() => setPage("home")}><img src="./icon.svg" /><span>くらしと通院メモ<small>通院の時に、自分の生活を見せるための記録</small></span></button><div className="headerActions"><button className="quietButton" onClick={() => setPage("help")}>使い方</button><button className="quietButton" onClick={() => setPage("settings")}>設定</button></div></header>{notice && <p className="notice" role="status">{notice}</p>}{page === "home" && <Home entries={entries} onGo={setPage} onExport={exportAll} onImport={() => importRef.current?.click()} />}{page === "record" && <Record date={activeDate} draft={draft} visible={visible} extrasEnabled={extras.filter(([k]) => settings.enabledExtras[k])} customItems={settings.customItems ?? []} setDate={setActiveDate} setDraft={setDraft} onSave={() => void save()} onClose={() => void save(true)} />}{page === "history" && <History entries={entries} onOpen={(d) => { setActiveDate(d); setPage("record"); }} />}{page === "clinic" && <Clinic entries={entries} settings={settings} onSettings={() => setPage("settings")} onCopy={(text) => navigator.clipboard.writeText(text).then(() => setNotice("通院時に見る・見せるメモをコピーしたよ。"))} onDownload={download} />}{page === "settings" && <Settings settings={settings} onChange={(next) => void saveSettings(next)} />}{page === "help" && <Help />}{<input ref={importRef} className="hidden" type="file" accept="application/json" onChange={(e) => { const f = e.target.files?.[0]; if (f) void importJson(f); e.currentTarget.value = ""; }} />}</main>;
}

function Home({ entries, onGo, onExport, onImport }: { entries: LifeEntry[]; onGo: (p: Page) => void; onExport: () => void; onImport: () => void }) { const current = entries.find((e) => e.date === today()); return <section className="home"><p className="eyebrow">{dateText(today())}</p><h1>{current && meaningful(current) ? "今日のことは、もう残っている。" : "今日のことを残す。"}</h1><p className="intro">通院時に、前回の診察から今日までの生活や状況を、自分の言葉で見せるための生活記録。</p><button className="primaryAction" onClick={() => onGo("record")}>今日を記録する <span>→</span></button><div className="homeLinks"><button onClick={() => onGo("clinic")}>通院時に見る・見せるメモ <span>期間と項目を選んでコピー・保存</span></button><button onClick={() => onGo("history")}>過去の記録を見る <span>前の日にも書き足せる</span></button><button onClick={() => onGo("settings")}>項目を整える <span>自分用の項目を作る・隠す</span></button><button onClick={onExport}>すべてをJSONにする <span>端末のダウンロードへ保存</span></button><button onClick={onImport}>JSONを読み込む <span>以前に保存した記録を戻す</span></button></div></section>; }
function Record({ date, draft, visible, extrasEnabled, customItems, setDate, setDraft, onSave, onClose }: { date: string; draft: LifeEntry; visible: Record<string, boolean>; extrasEnabled: readonly (readonly [string, string])[]; customItems: string[]; setDate: (d: string) => void; setDraft: (e: LifeEntry) => void; onSave: () => void; onClose: () => void }) { const time = (label: string, key: "bedtimePrev" | "wakeTime") => <label className="timeField"><span>{label}</span><select value={draft[key]} onChange={(e) => setDraft({ ...draft, [key]: e.target.value })}><option value="">まだ書いていない</option>{times.map((v) => <option key={v}>{v}</option>)}</select></label>; return <section className="paper"><div className="pageTitle"><div><p className="eyebrow">一日の記録</p><h1>{dateText(date)}</h1></div><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></div>{visible.sleep && <div className="formBlock">{time("前夜に寝た時刻", "bedtimePrev")}{time("今朝起きた時刻", "wakeTime")}</div>}{visible.meals && <Checks title="食事" choices={[["breakfast", "朝食"], ["lunch", "昼食"], ["dinner", "夕食"]]} values={draft.meals} onChange={(k) => setDraft({ ...draft, meals: { ...draft.meals, [k]: !draft.meals[k as keyof LifeEntry["meals"]] } })} />}{visible.medicine && <Checks title="薬" choices={[["medicine", "薬を飲んだ"]]} values={{ medicine: draft.medicine }} onChange={() => setDraft({ ...draft, medicine: !draft.medicine })} />}{extrasEnabled.length > 0 && <Checks title="今日したこと" choices={extrasEnabled} values={draft.activities} onChange={(k) => setDraft({ ...draft, activities: { ...draft.activities, [k]: !draft.activities[k] } })} />}{customItems.length > 0 && <Checks title="自分で作った項目" choices={customItems.map((v) => [v, v])} values={draft.activities} onChange={(k) => setDraft({ ...draft, activities: { ...draft.activities, [k]: !draft.activities[k] } })} />}{visible.note && <label className="noteField"><span>今日の日記</span><textarea value={draft.note} onChange={(e) => setDraft({ ...draft, note: e.target.value })} placeholder={prompts[new Date(date).getDate() % prompts.length]} rows={5} /></label>}{visible.trouble && <label className="noteField"><span>困りごとのメモ（通院時用）</span><small>通院メモに入れるかは、その都度選べる。</small><textarea value={draft.troubleNote ?? ""} onChange={(e) => setDraft({ ...draft, troubleNote: e.target.value })} rows={3} /></label>}<div className="recordActions"><button className="softButton" onClick={onClose}>今日はここまで</button><button className="primaryAction small" onClick={onSave}>記録を残す <span>✦</span></button></div></section>; }
function Checks({ title, choices, values, onChange }: { title: string; choices: readonly (readonly [string, string])[]; values: Record<string, boolean>; onChange: (k: string) => void }) { return <fieldset className="checkGroup"><legend>{title}</legend><div>{choices.map(([k, label]) => <label key={k} className={values[k] ? "checked" : ""}><input type="checkbox" checked={Boolean(values[k])} onChange={() => onChange(k)} /><i>✦</i>{label}</label>)}</div></fieldset>; }
function History({ entries, onOpen }: { entries: LifeEntry[]; onOpen: (d: string) => void }) { return <section className="paper"><p className="eyebrow">過去の記録</p><h1>記録をひらく</h1>{entries.length ? <div className="pastList">{entries.map((e) => <button key={e.date} onClick={() => onOpen(e.date)}><span>{dateText(e.date)}</span><small>{meaningful(e) ? "記録あり" : "日付だけ"}</small><b>›</b></button>)}</div> : <p className="empty">まだ記録はないよ。最初の一頁は、今日からで大丈夫。</p>}</section>; }
function Clinic({ entries, settings, onSettings, onCopy, onDownload }: { entries: LifeEntry[]; settings: AppSettings; onSettings: () => void; onCopy: (t: string) => void; onDownload: (d: unknown, f: string) => void }) { const [days, setDays] = useState(settings.clinicDays ?? 30), [includeTroubles, setIncludeTroubles] = useState(Boolean(settings.clinicFields?.trouble)); const fields = { ...defaults().clinic, ...(settings.clinicFields ?? {}), trouble: includeTroubles }; const period = useMemo(() => entries.filter((e) => days === "all" || e.date >= localDate(Number(days) - 1)), [entries, days]); const report = reportFor(period, days, fields); return <section className="paper clinic"><p className="eyebrow">通院メモ</p><h1>通院時に見る・見せるメモ</h1><p className="clinicNote">前回の診察から今日までの生活や状況を、書いたぶんだけ整える。</p><fieldset className="settingsGroup"><legend>見る期間</legend><div className="periodButtons">{([7, 14, 30, 60, 90, "all"] as const).map((v) => <button key={v} className={days === v ? "selected" : ""} onClick={() => setDays(v)}>{v === "all" ? "すべて" : `過去${v}日`}</button>)}</div></fieldset><section className="clinicReport"><h2>この内容を見せる</h2><p>設定で選んだ項目だけが表示される。</p><label><input type="checkbox" checked={includeTroubles} onChange={(e) => setIncludeTroubles(e.target.checked)} />困りごとのメモも、今回だけ含める</label><pre>{report}</pre><div className="reportActions"><button className="softButton" onClick={() => onCopy(report)}>メモをコピー</button><button className="softButton" onClick={() => onDownload({ app: "kurashi-tsuin-memo", exportedAt: new Date().toISOString(), period: days, fields, entries: period }, `tsuin-memo-${today()}.json`)}>この期間をJSONにする</button></div><small>JSONは端末の「ダウンロード」へファイルとして保存される。</small></section><button className="quietButton dark" onClick={onSettings}>表示する項目を設定する</button></section>; }
function reportFor(entries: LifeEntry[], days: number | "all", fields: Record<ClinicField, boolean>) { const text = days === "all" ? "記録したすべての期間" : `過去${days}日`; const count = (k: string) => entries.filter((e) => e.activities[k]).length; const lines = [`通院時に見る・見せるメモ（${text}）`, `記録のある日: ${entries.length}日`]; if (fields.meals) lines.push(`食事: ${entries.reduce((n, e) => n + Number(e.meals.breakfast) + Number(e.meals.lunch) + Number(e.meals.dinner), 0)}回（朝・昼・夕として記録した分）`); if (fields.medicine) lines.push(`薬の記録: ${entries.filter((e) => e.medicine).length}日（記録した日）`); if (fields.bath) lines.push(`入浴: ${count("bath")}日（記録した日）`); if (fields.work) lines.push(`仕事: ${count("work")}日（記録した日）`); if (fields.condition) lines.push(`体調不良: ${count("condition")}日（記録した日）`); if (fields.recorded) lines.push(`日記を書いた日: ${entries.filter((e) => e.note.trim()).length}日`); if (fields.trouble) { const notes = entries.filter((e) => e.troubleNote?.trim()); lines.push("", "困りごとのメモ", ...(notes.length ? notes.map((e) => `・${e.date.replace(/-/g, "/")}: ${e.troubleNote!.trim()}`) : ["・この期間に記録はありません"])); } return lines.join("\n"); }
function Settings({ settings, onChange }: { settings: AppSettings; onChange: (n: AppSettings) => void }) { const [name, setName] = useState(""), [removing, setRemoving] = useState<string>(); const base = defaults(), visible = { ...base.visible, ...(settings.visibleSections ?? {}) }, clinic = { ...base.clinic, ...(settings.clinicFields ?? {}) }, custom = settings.customItems ?? []; const add = () => { const value = name.trim(); if (!value || custom.includes(value)) return; onChange({ ...settings, customItems: [...custom, value] }); setName(""); }; const remove = () => { if (!removing) return; onChange({ ...settings, customItems: custom.filter((v) => v !== removing) }); setRemoving(undefined); }; return <section className="paper"><p className="eyebrow">設定</p><h1>項目を整える</h1><fieldset className="settingsGroup"><legend>記録する項目</legend><p>外しても、過去に書いた記録は消えない。</p>{coreItems.map(([k, label]) => <label key={k}><input type="checkbox" checked={visible[k]} onChange={() => onChange({ ...settings, visibleSections: { ...visible, [k]: !visible[k] } })} />{label}</label>)}{extras.map(([k, label]) => <label key={k}><input type="checkbox" checked={Boolean(settings.enabledExtras[k])} onChange={() => onChange({ ...settings, enabledExtras: { ...settings.enabledExtras, [k]: !settings.enabledExtras[k] } })} />{label}</label>)}</fieldset><fieldset className="settingsGroup"><legend>自分で作る項目</legend><p>例: 朝の薬（ミヤBM）、散歩、家事、リハビリ。作った項目は記録画面に出る。</p><div className="itemAdd"><input value={name} onChange={(e) => setName(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); add(); } }} placeholder="名前を書く" /><button className="softButton" onClick={add}>追加</button></div><div className="itemList">{custom.map((v) => <span key={v}>{v}<button onClick={() => setRemoving(v)}>削除</button></span>)}</div>{removing && <div className="deleteConfirm"><p>「{removing}」を項目一覧から削除する？</p><small>過去の記録は消えない。</small><div><button className="softButton" onClick={() => setRemoving(undefined)}>やめる</button><button className="rustButton" onClick={remove}>削除する</button></div></div>}</fieldset><fieldset className="settingsGroup"><legend>通院メモに表示する項目</legend><p>コピーとJSONに入れる項目を選ぶ。困りごとのメモは通院画面でも毎回確認できる。</p>{clinicItems.map(([k, label]) => <label key={k}><input type="checkbox" checked={clinic[k]} onChange={() => onChange({ ...settings, clinicFields: { ...clinic, [k]: !clinic[k] } })} />{label}</label>)}</fieldset><fieldset className="settingsGroup colorSecret"><legend>色を変える（そっと）</legend><p>記録の内容は変わらない。落ち着く一冊を選べる。</p><div className="themeChoices">{([ ["night", "夜の書斎"], ["paper", "生成りの紙"], ["forest", "深い森"], ["rose", "葡萄の余韻"] ] as const).map(([theme, label]) => <button key={theme} className={settings.theme === theme ? `selected ${theme}` : theme} onClick={() => onChange({ ...settings, theme })}>{label}</button>)}</div></fieldset><p className="codeDate">コード最終更新日: 2026年7月21日</p></section>; }
function Help() { return <section className="paper help"><p className="eyebrow">使い方</p><h1>通院の時に、生活を伝えるための記録</h1><ol><li><b>今日を記録する</b><br />睡眠、食事、薬、今日したことや日記を残す。項目は設定で増減できる。</li><li><b>通院時に見る・見せるメモ</b><br />見たい期間と表示項目を選び、画面を見せるかコピーする。</li><li><b>JSONにする</b><br />トップ画面のボタンから、全記録を端末のダウンロードにJSONファイルとして保存する。通院メモでは選んだ期間だけ保存できる。</li><li><b>自分で作る項目</b><br />朝の薬（ミヤBM）など、自分に必要な項目を追加できる。不要になった項目は、確認して一覧から外せる。</li><li><b>ホーム画面に追加</b><br />スマホのブラウザのメニューから「ホーム画面に追加」を選ぶと、アプリのように開ける。</li></ol><p className="footnote">このアプリは医療判断や診断をしない。記録がない日は、何もしていないという意味にはならない。</p></section>; }
